DROP TABLE AUDIT_CONNECTIONS CASCADE CONSTRAINTS;

CREATE TABLE AUDIT_CONNECTIONS
(
  UNIQUE_SESSION_ID    VARCHAR2(12 BYTE)        NOT NULL,
  SID                  NUMBER(6),
  SERIAL_NO            NUMBER(6),
  INST_NO              NUMBER(6),
  USERNAME             VARCHAR2(128 BYTE)       NOT NULL,
  OSUSER               VARCHAR2(30 BYTE),
  MACHINE              VARCHAR2(64 BYTE),
  IP_ADDRESS           VARCHAR2(45 BYTE),
  SERVICE_NAME         VARCHAR2(500 BYTE),
  PROGRAM              VARCHAR2(128 BYTE),
  MODULE               VARCHAR2(128 BYTE),
  AUTHENTICATION_TYPE  VARCHAR2(128 BYTE),
  LOGON_TIME           TIMESTAMP(6)             NOT NULL,
  CONNECTION_STATUS    VARCHAR2(30 BYTE)
)
ROW STORE COMPRESS ADVANCED
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARTITION BY RANGE (LOGON_TIME)
INTERVAL( INTERVAL '1' DAY)
(  
  PARTITION OUT_OF_BOUNDS VALUES LESS THAN (TIMESTAMP' 2000-01-01 00:00:00')
    LOGGING
    ROW STORE COMPRESS ADVANCED
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               )
)
NOCACHE
MONITORING;
